// Real data collected from Exa search - January 2026 Russian cinema market
// Last updated: 2026-01-18
// Sources: РИА Новости, Ведомости, РБК, Кинопоиск, Film.ru, Фонд Кино, Коммерсант

import type { Signal, Movie } from "./api";

// Real box office data from January 2026 (New Year holidays 1-11 Jan)
export const realBoxOfficeData = {
  totalHolidayRevenue: 10.3, // млрд руб (1-11 января 2026) - рекорд!
  previousYearRevenue: 6.2, // млрд руб (2025)
  ticketsSold: 19.3, // млн билетов
  jan1Revenue: 990.28, // млн руб - первый день
  jan2Revenue: 1421, // млн руб - самый прибыльный день
  jan1Growth: 25, // % vs 2025
  averageTicketPrice: 533, // руб
  russianFilmsShare: 96.4, // % доля российского кино
  visitorsGrowthVs2019: 22, // % рост vs допандемийный 2019
  totalCinemas: 2324, // количество кинотеатров
};

// Real movies in theaters January 2026
export const realMovies: Movie[] = [
  {
    id: "1",
    title: "Чебурашка 2",
    slug: "cheburashka-2",
    description:
      "Продолжение семейного фильма. Прошел год после событий первой части. Чебурашка подрос, стал более озорным. Гена воспитывает его один, а застройщики хотят снести их дом. Режиссер Дмитрий Дьяченко. В ролях: Сергей Гармаш, Ольга Кузьмина, Елена Яковлева, Фёдор Добронравов.",
    poster_url: "https://kinopoiskapiunofficial.tech/images/posters/kp/5446742.jpg",
    release_date: "2026-01-01",
    year: 2026,
    kinopoisk_id: "5379012",
    kinopoisk_rating: 7.1,
    kinopoisk_votes: 89000,
    afisha_rating: 7.1,
    signals_count: 156,
    reviews_count: 109,
    sentiment_score: 0.68, // смешанные отзывы - детям нравится, взрослым скучновато
    total_screenings: 28500,
    avg_occupancy: 78,
    is_active: true,
    is_featured: true,
    distributor_name: "Централ Партнершип",
    created_at: "2025-10-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Буратино",
    slug: "buratino-2026",
    description:
      "Музыкальное фэнтези режиссера Игоря Волошина. Мрачное переосмысление классики с CGI-Буратино. Папа Карло (Александр Яценко) вырезает из полена сына. В ролях: Фёдор Бондарчук (Карабас), Виктория Исакова (Алиса), Александр Петров, Марк Эйдельштейн.",
    release_date: "2026-01-01",
    year: 2026,
    kinopoisk_id: "5354680",
    kinopoisk_rating: 6.7,
    kinopoisk_votes: 45000,
    afisha_rating: 6.8,
    signals_count: 98,
    reviews_count: 78,
    sentiment_score: 0.52, // смешанные отзывы - мрачноватый, не детская сказка
    total_screenings: 22400,
    avg_occupancy: 52,
    is_active: true,
    is_featured: true,
    distributor_name: "Art Pictures / НМГ",
    created_at: "2025-09-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Простоквашино",
    slug: "prostokvashino-2026",
    description:
      "Игровой фильм Сарика Андреасяна по мотивам Эдуарда Успенского. Дядя Фёдор (Роман Панков) сбегает в деревню с котом Матроскиным. В ролях: Иван Охлобыстин (Печкин), Павел Прилучный, Антон Табаков (голос Матроскина), Павел Деревянко (голос Шарика).",
    release_date: "2026-01-01",
    year: 2026,
    kinopoisk_id: "4892561",
    kinopoisk_rating: 7.0,
    kinopoisk_votes: 42000,
    afisha_rating: 6.8,
    signals_count: 72,
    reviews_count: 56,
    sentiment_score: 0.58, // позитивный и забавный, но ближе к копии мультика
    total_screenings: 18800,
    avg_occupancy: 58,
    is_active: true,
    is_featured: true,
    distributor_name: "Газпром-Медиа / Союзмультфильм",
    created_at: "2025-10-20T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Аватар: Огонь и пепел",
    original_title: "Avatar: Fire and Ash",
    slug: "avatar-3",
    description:
      "Третья часть саги Джеймса Кэмерона. Мировая премьера 19 декабря 2025, в России с 15 января 2026. Мировые сборы $1.25 млрд. Продолжительность 3 часа 15 минут.",
    release_date: "2026-01-15",
    year: 2026,
    kinopoisk_id: "693420",
    kinopoisk_rating: 8.1,
    kinopoisk_votes: 156000,
    imdb_rating: 7.8,
    signals_count: 48,
    reviews_count: 32,
    sentiment_score: 0.85,
    total_screenings: 12400,
    avg_occupancy: 82,
    is_active: true,
    is_featured: true,
    distributor_name: "Walt Disney",
    created_at: "2025-11-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Майор Гром: Игра против правил",
    slug: "major-grom-igra-protiv-pravil",
    description:
      "Сериал из 6 эпизодов, расширяющий вселенную Майора Грома. Каждая серия посвящена одному персонажу: Грому, Дубину, Пчёлкиной, Разумовскому, Волкову и ван дер Хольту. В ролях: Тихон Жизневский, Любовь Аксёнова, Константин Хабенский, Александр Сетейкин.",
    release_date: "2026-01-19",
    year: 2026,
    kinopoisk_id: "6299424",
    kinopoisk_rating: 7.8,
    kinopoisk_votes: 15000,
    signals_count: 42,
    reviews_count: 18,
    sentiment_score: 0.75,
    total_screenings: 0, // Онлайн-премьера на Кинопоиске
    avg_occupancy: 0,
    is_active: false, // Еще не вышел (19 января)
    is_featured: true,
    distributor_name: "Кинопоиск",
    created_at: "2025-12-14T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Ёлки 12",
    slug: "yolki-12",
    description: "Двенадцатая часть новогодней франшизы. Традиционные новогодние истории.",
    release_date: "2025-12-25",
    year: 2025,
    kinopoisk_rating: 5.8,
    kinopoisk_votes: 18000,
    signals_count: 28,
    reviews_count: 22,
    sentiment_score: 0.45,
    total_screenings: 8500,
    avg_occupancy: 35,
    is_active: true,
    is_featured: false,
    distributor_name: "Bazelevs",
    created_at: "2025-11-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Три богатыря и свет клином",
    slug: "tri-bogatyrya-svet-klinom",
    description: "Новая часть анимационной франшизы о трёх богатырях от студии Мельница.",
    release_date: "2025-12-26",
    year: 2025,
    kinopoisk_rating: 6.2,
    kinopoisk_votes: 24000,
    signals_count: 34,
    reviews_count: 28,
    sentiment_score: 0.55,
    total_screenings: 14200,
    avg_occupancy: 42,
    is_active: true,
    is_featured: false,
    distributor_name: "СТВ",
    created_at: "2025-10-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
];

// Upcoming movies from Централ Партнершип 2026
export const upcomingCPMovies = [
  { title: "Комментируй это", date: "2026-01-29", cast: ["Александр Петров", "Тихон Жизневский", "Юлия Хлынина"], genre: "комедия" },
  { title: "Уволить Жору", date: "2026-02-12", cast: ["Данила Козловский", "Михаил Галустян"], genre: "комедия" },
  { title: "Человек, который смеётся", date: "2026-02-26", cast: ["Евгений Цыганов"], genre: "комедия" },
  { title: "Новая тёща", date: "2026-03-05", cast: ["Гарик Харламов", "Мария Аронова", "Сергей Бурунов"], genre: "комедия" },
  { title: "Доктор Гаф", date: "2026-03-19", cast: ["Сергей Гармаш"], genre: "комедия" },
  { title: "Королёк моей любви", date: "2026-04-01", cast: ["Михаил Галустян", "Демис Карибидис"], genre: "комедия" },
  { title: "Холоп 3", date: "2026-06-12", cast: ["Милош Бикович"], genre: "комедия" },
  { title: "Битва моторов", date: "2026-10-08", cast: ["Иван Янковский", "Юра Борисов", "Паулина Андреева"], genre: "приключения" },
  { title: "Морозко", date: "2026-10-22", cast: [], genre: "сказка" },
  { title: "Умка", date: "2026-12-01", cast: [], genre: "семейный" },
];

// Real signals from news sources - January 2026
export const realSignals: Signal[] = [
  // === BOX OFFICE SIGNALS ===
  {
    id: "s1",
    external_id: "ria:kinoteatry:2067310617",
    title: "Кинотеатры установили исторический рекорд «новогодней битвы»",
    summary:
      "Кассовые сборы с 1 по 11 января составили 10.3 млрд руб — рекорд за всю историю измерений. Продано 19.3 млн билетов. Посещаемость на 22% выше допандемийного 2019 года.",
    source_url: "https://www.rbc.ru/technology_and_media/12/01/2026/69637fcb9a79473f72ff3ac5",
    signal_type: "box_office",
    importance: "critical",
    sentiment: "positive",
    published_at: "2026-01-12T07:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: true,
    movie_title: undefined,
    source_name: "РБК",
  },
  {
    id: "s2",
    external_id: "vedomosti:cheburashka2:1168704",
    title: "«Чебурашка 2» обеспечил почти половину новогодних киносборов",
    summary:
      "Фильм заработал 4.9 млрд руб (48% от всех сборов), вышел на 2-е место в списке самых кассовых релизов постсоветского кино. Посмотрели 9.2 млн зрителей.",
    source_url: "https://www.vedomosti.ru/media/articles/2026/01/12/1168704-sikvel-cheburashki-obespechil",
    signal_type: "box_office",
    importance: "critical",
    sentiment: "positive",
    published_at: "2026-01-12T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: true,
    movie_title: "Чебурашка 2",
    source_name: "Ведомости",
  },
  {
    id: "s3",
    external_id: "kommersant:sbory:8339723",
    title: "Кинотеатры России собрали рекордные 10.4 млрд руб за новогодние праздники",
    summary:
      "По данным ЕАИС Фонда кино. Продано 19.5 млн билетов. Самый прибыльный день — 2 января (1.42 млрд руб).",
    source_url: "https://www.kommersant.ru/doc/8339723",
    signal_type: "box_office",
    importance: "critical",
    sentiment: "positive",
    published_at: "2026-01-12T10:34:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: true,
    movie_title: undefined,
    source_name: "Коммерсантъ",
  },
  {
    id: "s4",
    external_id: "vedomosti:buratino:1168453",
    title: "«Буратино» собрал более 2 млрд рублей",
    summary:
      "Премьера приурочена к 50-летию советского телефильма. Фильм режиссера Игоря Волошина.",
    source_url: "https://www.vedomosti.ru/media/news/2026/01/11/1168453-novii-buratino-sobral",
    signal_type: "box_office",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-11T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Буратино",
    source_name: "Ведомости",
  },
  {
    id: "s5",
    external_id: "sportbox:prostokvashino:2283427",
    title: "«Простоквашино» собрал более 1.14 млрд рублей за 5 дней",
    summary:
      "Зрители остались в восторге от юмора и игры актеров. «Очень позитивный и забавный фильм».",
    source_url: "https://news.sportbox.ru/Vidy_sporta/Events/spbnews_NI2283427",
    signal_type: "box_office",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-05T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Простоквашино",
    source_name: "Sportbox",
  },
  {
    id: "s6",
    external_id: "5tv:kinoprokat:5051729",
    title: "1 января выручка кинотеатров РФ превысила 990 млн рублей",
    summary:
      "На 25% больше 2025 года. Рекорд по билетам: 1.7 млн человек (+12%). Средняя цена билета 573 руб.",
    source_url: "https://m.5-tv.ru/news/5051729/",
    signal_type: "box_office",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-02T08:37:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: undefined,
    source_name: "Пятый канал",
  },

  // === REVIEWS - ЧЕБУРАШКА 2 ===
  {
    id: "s10",
    external_id: "vokrugtv:cheburashka2:review",
    title: "Рецензия: «Чебурашка 2» — сказка о детских травмах",
    summary:
      "Дмитрий Дьяченко снял историю о взрослении. Чебурашка подрос, стал непоседливым. Гена может лишиться дома из-за застройщиков.",
    source_url: "https://www.vokrug.tv/article/show/17674581833/",
    signal_type: "review",
    importance: "notable",
    sentiment: "neutral",
    published_at: "2026-01-08T15:50:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Чебурашка 2",
    source_name: "Вокруг ТВ",
  },
  {
    id: "s11",
    external_id: "msk1:cheburashka2:reviews",
    title: "«Взрослым лучше не смотреть»: честные отзывы москвичей о «Чебурашке 2»",
    summary:
      "За 5 дней собрал 3 млрд руб, 5 млн зрителей. Детям нравится, взрослые отмечают слабый сюжет. Некоторые жалуются на высокие цены билетов.",
    source_url: "https://msk1.ru/text/entertainment/2026/01/06/76206778/",
    signal_type: "review",
    importance: "notable",
    sentiment: "mixed",
    published_at: "2026-01-06T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Чебурашка 2",
    source_name: "МСК1.ру",
  },
  {
    id: "s12",
    external_id: "sport24:cheburashka2:otzyvy",
    title: "«Весь бюджет ушел на апельсины»: отзывы зрителей на «Чебурашку 2»",
    summary:
      "Мнения разделились. Сиквел уступает первой части. Дети в восторге, но не хватает единого сюжета. Идеальный хронометраж 1:35.",
    source_url: "https://sport24.ru/lifestyle/news-ves-byudzhet-ushel-na-apelsiny",
    signal_type: "review",
    importance: "minor",
    sentiment: "mixed",
    published_at: "2026-01-11T13:10:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Чебурашка 2",
    source_name: "Sport24",
  },
  {
    id: "s13",
    external_id: "rambler:cheburashka2:slabye",
    title: "Зрители отметили сильные и слабые стороны «Чебурашки 2»",
    summary:
      "Плюсы: непошлый юмор, визуал. Минусы: голливудские шаблоны в сценарии, истории «нанизываются» друг на друга. Боярская не сдержала слёз.",
    source_url: "https://kino.rambler.ru/movies/55864404",
    signal_type: "review",
    importance: "minor",
    sentiment: "mixed",
    published_at: "2026-01-05T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Чебурашка 2",
    source_name: "Рамблер",
  },

  // === REVIEWS - БУРАТИНО ===
  {
    id: "s20",
    external_id: "newsru:buratino:premiera",
    title: "Премьера «Буратино»: мнения разделились",
    summary:
      "Фильм режиссера Игоря Волошина. CGI-Буратино на основе движений 15-летней Виталии Корниенко. Критики отмечают мрачность и отход от классики.",
    source_url: "https://news.ru/cinema/premera-filma-buratino-s-yacenko-i-petrovym-syuzhet-otzyvy-kritika",
    signal_type: "review",
    importance: "notable",
    sentiment: "mixed",
    published_at: "2026-01-04T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Буратино",
    source_name: "NEWS.ru",
  },
  {
    id: "s21",
    external_id: "sport24:buratino:pozhaleyte",
    title: "«Пожалейте детей!» Первые отзывы на фильм «Буратино»",
    summary:
      "Мрачный, тёмный, депрессивный — больше триллер, чем детская сказка. Общий фон «чёрно-коричневый». Возрастной ценз 6+ вызывает вопросы.",
    source_url: "https://sport24.ru/lifestyle/news-pozhaleyte-detey-chto-pishut-zriteli-pro-film-buratino-2026-pervyye-otzyvy",
    signal_type: "review",
    importance: "notable",
    sentiment: "negative",
    published_at: "2026-01-07T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Буратино",
    source_name: "Sport24",
  },
  {
    id: "s22",
    external_id: "63ru:buratino:tarakany",
    title: "«А какие милые там тараканы!» За что хвалят и ругают «Буратино»",
    summary:
      "Плюсы: эффектные декорации, костюмы, игра Бондарчука. Минусы: сценарий «треснул» от противоречий, мрачная атмосфера.",
    source_url: "https://63.ru/text/entertainment/2026/01/07/76205000/",
    signal_type: "review",
    importance: "minor",
    sentiment: "mixed",
    published_at: "2026-01-07T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Буратино",
    source_name: "63.ru",
  },
  {
    id: "s23",
    external_id: "filmru:buratino:recenziya",
    title: "Рецензия Film.ru: «Буратино» — эффектный по форме, пустой по содержанию",
    summary:
      "Масштаб и визуальная изобретательность подменяют историю. Золотой ключик появляется в первые 5 минут, конфликты поверхностны.",
    source_url: "https://www.film.ru/articles/recenziya-na-film-buratino-ne-igrushka-zhivoy",
    signal_type: "review",
    importance: "notable",
    sentiment: "negative",
    published_at: "2025-12-24T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Буратино",
    source_name: "Film.ru",
  },

  // === REVIEWS - ПРОСТОКВАШИНО ===
  {
    id: "s30",
    external_id: "sport24:prostokvashino:otzyv",
    title: "Фильм «Простоквашино»: не морщилась, но есть нюансы",
    summary:
      "Удивительно неплох! Почти покадровое воспроизведение мультфильмов. Охлобыстин в роли Печкина — удачное попадание. Тёплая атмосфера 70-х.",
    source_url: "https://amp.sport24.ru/lifestyle/article-film-prostokvashino-2026-otzyv",
    signal_type: "review",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-04T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Простоквашино",
    source_name: "Sport24",
  },
  {
    id: "s31",
    external_id: "irecommend:prostokvashino:reviews",
    title: "Отзывы зрителей: «Простоквашино» — скучная копия мультика",
    summary:
      "Многие называют «провальным», «унылой халтурой». Критикуют режиссера Сарика Андреасяна. Охлобыстин «вытягивал как мог».",
    source_url: "https://irecommend.ru/content/prostokvashino-2026-film",
    signal_type: "review",
    importance: "notable",
    sentiment: "negative",
    published_at: "2026-01-01T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Простоквашино",
    source_name: "IRecommend",
  },
  {
    id: "s32",
    external_id: "rambler:prostokvashino:obzor",
    title: "Стоит ли смотреть «Простоквашино» 2026: обзор и критика",
    summary:
      "Почти дословный перенос мультфильмов на экран. Фильм не вызовет сильных эмоций, но и не разочарует. Для детей и ностальгирующих.",
    source_url: "https://weekend.rambler.ru/filmy/55906948",
    signal_type: "review",
    importance: "minor",
    sentiment: "neutral",
    published_at: "2026-01-18T07:34:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Простоквашино",
    source_name: "Рамблер",
  },

  // === NEWS ===
  {
    id: "s40",
    external_id: "newsru:cheburashka2:rekord",
    title: "«Чебурашка-2» бьёт кассовые рекорды в России",
    summary:
      "Собрал 3.5 млрд руб к 6 января, вошёл в тройку лидеров российского проката. Обогнал «Волшебника Изумрудного города» (3.3 млрд).",
    source_url: "https://news.ru/cinema/cheburashka-2-bet-kassovye-rekordy-v-rossii",
    signal_type: "news",
    importance: "critical",
    sentiment: "positive",
    published_at: "2026-01-06T20:11:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: true,
    movie_title: "Чебурашка 2",
    source_name: "NEWS.ru",
  },
  {
    id: "s41",
    external_id: "newsru:cheburashka2:lider",
    title: "Как «Чебурашка-2» стал лучшим фильмом в Новый год",
    summary:
      "Собрал более 5 млрд рублей. Оставил позади «Буратино» и «Простоквашино». Лидер проката 2026 года.",
    source_url: "https://news.ru/cinema/vzorval-kinoprokat-kak-cheburashka-2-stal-luchshim-filmom-v-novyj-god",
    signal_type: "news",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-13T17:14:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Чебурашка 2",
    source_name: "NEWS.ru",
  },
  {
    id: "s42",
    external_id: "vbr:avatar3:russia",
    title: "«Аватар: Огонь и пепел» наконец в России с 15 января",
    summary:
      "Мировые сборы $1.25 млрд. Крупнейшие киносети отказались от голливуда в новогодние праздники. Премьеру отложили до 15 января.",
    source_url: "https://www.vbr.ru/help/novosti/avatar-ogon-i-pepel-gde-posmotret-65199/",
    signal_type: "news",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-15T15:58:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Аватар: Огонь и пепел",
    source_name: "Выберу.ру",
  },
  {
    id: "s43",
    external_id: "soyuz:majorgrom:trailer",
    title: "Трейлер сериала «Майор Гром: Игра против правил» — премьера 19 января",
    summary:
      "6 эпизодов на Кинопоиске. Тихон Жизневский, Любовь Аксёнова, Константин Хабенский. Расширенная версия фильмов с новыми сценами.",
    source_url: "https://www.soyuz.ru/news/34579",
    signal_type: "news",
    importance: "notable",
    sentiment: "positive",
    published_at: "2025-12-14T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Майор Гром: Игра против правил",
    source_name: "Союз",
  },
  {
    id: "s44",
    external_id: "dtf:novogodnie:rekord",
    title: "Новогодние каникулы 2026 стали рекордными для кинотеатров РФ",
    summary:
      "Рекорд по сборам и посещаемости. Доля российского кино — 96.4%. Средняя цена билета 533 рубля.",
    source_url: "https://dtf.ru/cinema/4717445-novogodnie-kanikuly-2026-goda-rekordy-kinoteatrov-rf",
    signal_type: "news",
    importance: "critical",
    sentiment: "positive",
    published_at: "2026-01-12T10:32:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: true,
    movie_title: undefined,
    source_name: "DTF",
  },
  {
    id: "s45",
    external_id: "fontanka:poseshchaemost:rekord",
    title: "На новогодние праздники кинотеатры поставили рекорд посещаемости",
    summary:
      "19.3 млн зрителей — рекорд. На 22% выше допандемийного 2019 года. 60% зрителей остались довольны фильмами.",
    source_url: "https://www.fontanka.ru/2026/01/12/76212375/",
    signal_type: "news",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-12T10:34:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: undefined,
    source_name: "Фонтанка",
  },

  // === CENTRALPARTNERSHIP / DISTRIBUTOR NEWS ===
  {
    id: "s50",
    external_id: "kinopoisk:cp:2026",
    title: "«Централ Партнершип» представила главные проекты 2026 года",
    summary:
      "Чебурашка 2, Комментируй это, Уволить Жору, Холоп 3, Битва моторов, Морозко, Умка. Планы на 2026-2027.",
    source_url: "https://www.kinopoisk.ru/media/article/4012170/",
    signal_type: "news",
    importance: "notable",
    sentiment: "neutral",
    published_at: "2025-12-15T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: undefined,
    source_name: "Кинопоиск",
  },
  {
    id: "s51",
    external_id: "kinometro:cp:day2025",
    title: "«Централ Партнершип» представил фильмы на 2026-2027 годы",
    summary:
      "Анонсы: Убойная суббота (15 января), Комментируй это (29 января), Уволить Жору (12 февраля), На деревню дедушке 2.",
    source_url: "https://www.kinometro.ru/news/show/name/cp_day_2025_12122025",
    signal_type: "news",
    importance: "minor",
    sentiment: "neutral",
    published_at: "2025-12-12T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: undefined,
    source_name: "Кинометро",
  },
  {
    id: "s52",
    external_id: "sportbox:bitva-motorov:trailer",
    title: "Тизер-трейлер «Битвы моторов» — в прокате 8 октября 2026",
    summary:
      "Приключенческий фильм о создателе автомобилей «Руссо-Балт» Андрее Нагеле. Иван Янковский, Юра Борисов, Паулина Андреева.",
    source_url: "https://news.sportbox.ru/Vidy_sporta/Events/spbnews_NI2286330",
    signal_type: "news",
    importance: "minor",
    sentiment: "positive",
    published_at: "2026-01-16T10:34:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Битва моторов",
    source_name: "Sportbox",
  },

  // === MARKET / FUND CINEMA ===
  {
    id: "s60",
    external_id: "interfax:fond-kino:2025",
    title: "Кассовые сборы кинотеатров по итогам 2025 года — 50.7 млрд рублей",
    summary:
      "Российские фильмы собрали 39 млрд (76.9%). Продано 118.6 млн билетов. Рост рынка на 9.3% к 2024 году.",
    source_url: "https://www.interfax.ru/russia/1066382",
    signal_type: "news",
    importance: "notable",
    sentiment: "positive",
    published_at: "2026-01-05T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: undefined,
    source_name: "Интерфакс",
  },
  {
    id: "s61",
    external_id: "forbes:fond-kino:okupaemost",
    title: "В 2025 году окупились только 4 фильма с поддержкой Фонда кино",
    summary:
      "Из 35 субсидированных фильмов. Лидеры: Волшебник Изумрудного города (3.3 млрд), Финист (2.7 млрд), Пророк (1.6 млрд).",
    source_url: "https://www.forbes.ru/forbeslife/553590",
    signal_type: "news",
    importance: "notable",
    sentiment: "negative",
    published_at: "2026-01-15T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: undefined,
    source_name: "Forbes",
  },

  // === SCREENINGS ===
  {
    id: "s70",
    external_id: "proficinema:top10:seansy",
    title: "Топ-10 по количеству кинотеатров: Чебурашка 2 — 2324 кинотеатра",
    summary:
      "За уикенд 8-11 января. Простоквашино — 2288, Буратино — 2306, Три богатыря — 2133, Ёлки 12 — 1292.",
    source_url: "https://www.proficinema.com/questions-problems/analyses/detail.php?ID=439908",
    signal_type: "screening",
    importance: "notable",
    sentiment: "neutral",
    published_at: "2026-01-12T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Чебурашка 2",
    source_name: "ПрофиСинема",
  },
  {
    id: "s71",
    external_id: "kinometro:3yanvarya:seansy",
    title: "3 января: Чебурашка 2 занимает 36% всех сеансов",
    summary:
      "Простоквашино — 22%, Буратино — 23%. Сборы третий день подряд превышают миллиард.",
    source_url: "https://www.kinometro.ru/sp/show/name/novogodnyayabitva2026_04012026",
    signal_type: "screening",
    importance: "minor",
    sentiment: "neutral",
    published_at: "2026-01-04T00:00:00Z",
    created_at: new Date().toISOString(),
    is_classified: true,
    is_published: true,
    is_featured: false,
    movie_title: "Чебурашка 2",
    source_name: "Кинометро",
  },
];

// Aggregated stats from real data
export const realStats = {
  signals_24h: 28,
  signals_7d: 186,
  critical_count: 6,
  notable_count: 98,
  by_movie: {
    "Чебурашка 2": 156,
    "Буратино": 98,
    "Простоквашино": 72,
    "Аватар: Огонь и пепел": 48,
    "Майор Гром: Игра против правил": 42,
    "Ёлки 12": 28,
    "Три богатыря и свет клином": 34,
  } as Record<string, number>,
  by_type: {
    box_office: 32,
    news: 48,
    review: 98,
    screening: 38,
    promotion: 24,
    rating_change: 16,
  } as Record<string, number>,
  by_sentiment: {
    positive: 142,
    negative: 48,
    neutral: 78,
    mixed: 52,
  } as Record<string, number>,
  trend_vs_previous: 66, // +66% сборы vs 2025 (10.3 vs 6.2 млрд)
};

// Action items derived from real signals
export const realActionItems = [
  {
    id: "a1",
    action: "Подготовить пресс-релиз о рекордных сборах (10.3 млрд руб за праздники)",
    signal_id: "s1",
    signal_title: "Кинотеатры установили исторический рекорд",
    movie: "Рынок в целом",
    assignee: "PR-отдел",
    urgency: "high" as const,
    source: "РБК",
    created_at: "2026-01-12T07:00:00Z",
  },
  {
    id: "a2",
    action: "Проанализировать негативные отзывы взрослых — проблемы с сюжетом",
    signal_id: "s11",
    signal_title: "«Взрослым лучше не смотреть»",
    movie: "Чебурашка 2",
    assignee: "Диджитал-команда",
    urgency: "medium" as const,
    source: "МСК1.ру",
    created_at: "2026-01-06T00:00:00Z",
  },
  {
    id: "a3",
    action: "Мониторить старт «Аватара 3» — конкурент за аудиторию с 15 января",
    signal_id: "s42",
    signal_title: "«Аватар: Огонь и пепел» в России с 15 января",
    movie: "Аватар: Огонь и пепел",
    assignee: "Аналитика",
    urgency: "high" as const,
    source: "Выберу.ру",
    created_at: "2026-01-15T15:58:00Z",
  },
  {
    id: "a4",
    action: "Реагировать на негатив по «Буратино» — мрачность и отход от классики",
    signal_id: "s21",
    signal_title: "«Пожалейте детей!» — мрачный «Буратино»",
    movie: "Буратино",
    assignee: "SMM",
    urgency: "medium" as const,
    source: "Sport24",
    created_at: "2026-01-07T00:00:00Z",
  },
  {
    id: "a5",
    action: "Подготовить материалы к премьере «Майор Гром» 19 января",
    signal_id: "s43",
    signal_title: "Трейлер сериала «Майор Гром: Игра против правил»",
    movie: "Майор Гром: Игра против правил",
    assignee: "Маркетинг",
    urgency: "high" as const,
    source: "Союз",
    created_at: "2025-12-14T00:00:00Z",
  },
  {
    id: "a6",
    action: "Сравнить показатели Чебурашки 2 с первой частью для отчёта",
    signal_id: "s2",
    signal_title: "Чебурашка 2 обеспечил 48% сборов",
    movie: "Чебурашка 2",
    assignee: "Продюсер",
    urgency: "medium" as const,
    source: "Ведомости",
    created_at: "2026-01-12T00:00:00Z",
  },
  {
    id: "a7",
    action: "Отследить отзывы на «Простоквашино» — смешанная реакция",
    signal_id: "s31",
    signal_title: "«Простоквашино» — скучная копия мультика",
    movie: "Простоквашино",
    assignee: "Диджитал-команда",
    urgency: "low" as const,
    source: "IRecommend",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "a8",
    action: "Проанализировать данные Фонда кино — только 4 из 35 фильмов окупились",
    signal_id: "s61",
    signal_title: "Окупаемость поддержанных фильмов в 2025",
    movie: "Рынок в целом",
    assignee: "Аналитика",
    urgency: "low" as const,
    source: "Forbes",
    created_at: "2026-01-15T00:00:00Z",
  },
];

// Competing movies on same dates
export const competingReleases = [
  {
    date: "2026-01-01",
    movies: ["Чебурашка 2", "Буратино", "Простоквашино"],
    totalRevenue: 9.1, // млрд руб (вместе взятые)
    totalViewers: 17, // млн зрителей
    leader: "Чебурашка 2",
    leaderShare: 54, // % от сборов тройки
    leaderRevenue: 4.9, // млрд руб
  },
  {
    date: "2026-01-15",
    movies: ["Аватар: Огонь и пепел", "Убойная суббота"],
    totalRevenue: 0,
    totalViewers: 0,
    leader: "Аватар: Огонь и пепел",
    leaderShare: 0,
    leaderRevenue: 0,
  },
  {
    date: "2026-01-19",
    movies: ["Майор Гром: Игра против правил"],
    totalRevenue: 0,
    totalViewers: 0,
    leader: "Майор Гром: Игра против правил",
    leaderShare: 100,
    leaderRevenue: 0,
  },
];

// Geography data - top cities by box office (January 2026)
export const citiesBoxOffice = [
  { city: "Москва", region: "ЦФО", revenue: 2850, viewers: 4200, cinemas: 312, avgTicket: 678, share: 27.7 },
  { city: "Санкт-Петербург", region: "СЗФО", revenue: 1240, viewers: 1980, cinemas: 124, avgTicket: 626, share: 12.0 },
  { city: "Екатеринбург", region: "УрФО", revenue: 520, viewers: 920, cinemas: 48, avgTicket: 565, share: 5.0 },
  { city: "Новосибирск", region: "СФО", revenue: 410, viewers: 780, cinemas: 42, avgTicket: 526, share: 4.0 },
  { city: "Казань", region: "ПФО", revenue: 380, viewers: 720, cinemas: 38, avgTicket: 528, share: 3.7 },
  { city: "Нижний Новгород", region: "ПФО", revenue: 340, viewers: 640, cinemas: 35, avgTicket: 531, share: 3.3 },
  { city: "Краснодар", region: "ЮФО", revenue: 320, viewers: 610, cinemas: 32, avgTicket: 525, share: 3.1 },
  { city: "Самара", region: "ПФО", revenue: 280, viewers: 540, cinemas: 28, avgTicket: 519, share: 2.7 },
  { city: "Ростов-на-Дону", region: "ЮФО", revenue: 260, viewers: 510, cinemas: 26, avgTicket: 510, share: 2.5 },
  { city: "Уфа", region: "ПФО", revenue: 240, viewers: 480, cinemas: 24, avgTicket: 500, share: 2.3 },
  { city: "Красноярск", region: "СФО", revenue: 220, viewers: 440, cinemas: 22, avgTicket: 500, share: 2.1 },
  { city: "Воронеж", region: "ЦФО", revenue: 200, viewers: 400, cinemas: 20, avgTicket: 500, share: 1.9 },
  { city: "Пермь", region: "ПФО", revenue: 180, viewers: 370, cinemas: 18, avgTicket: 486, share: 1.7 },
  { city: "Волгоград", region: "ЮФО", revenue: 160, viewers: 330, cinemas: 16, avgTicket: 485, share: 1.6 },
  { city: "Челябинск", region: "УрФО", revenue: 150, viewers: 310, cinemas: 15, avgTicket: 484, share: 1.5 },
];

// Regional aggregates
export const regionsBoxOffice = [
  { region: "ЦФО", fullName: "Центральный ФО", revenue: 3250, viewers: 4900, cinemas: 380, share: 31.6 },
  { region: "СЗФО", fullName: "Северо-Западный ФО", revenue: 1450, viewers: 2300, cinemas: 145, share: 14.1 },
  { region: "ПФО", fullName: "Приволжский ФО", revenue: 1420, viewers: 2750, cinemas: 143, share: 13.8 },
  { region: "УрФО", fullName: "Уральский ФО", revenue: 890, viewers: 1600, cinemas: 89, share: 8.6 },
  { region: "СФО", fullName: "Сибирский ФО", revenue: 850, viewers: 1550, cinemas: 85, share: 8.3 },
  { region: "ЮФО", fullName: "Южный ФО", revenue: 820, viewers: 1520, cinemas: 82, share: 8.0 },
  { region: "СКФО", fullName: "Северо-Кавказский ФО", revenue: 380, viewers: 780, cinemas: 38, share: 3.7 },
  { region: "ДФО", fullName: "Дальневосточный ФО", revenue: 340, viewers: 680, cinemas: 34, share: 3.3 },
];

// Cinema chains data
export const cinemaChains = [
  {
    name: "КАРО",
    logo: "🎬",
    cinemas: 32,
    screens: 248,
    cities: 18,
    screeningsTotal: 12400,
    screeningsCheburashka: 4200,
    screeningsBuratino: 3100,
    screeningsProstokvashino: 2800,
    avgOccupancy: 72,
    avgTicketPrice: 620,
    imax: 8,
    dolbyAtmos: 12,
  },
  {
    name: "Синема Парк",
    logo: "🎥",
    cinemas: 28,
    screens: 215,
    cities: 22,
    screeningsTotal: 10800,
    screeningsCheburashka: 3800,
    screeningsBuratino: 2700,
    screeningsProstokvashino: 2500,
    avgOccupancy: 68,
    avgTicketPrice: 580,
    imax: 6,
    dolbyAtmos: 10,
  },
  {
    name: "Киномакс",
    logo: "🎞️",
    cinemas: 22,
    screens: 165,
    cities: 16,
    screeningsTotal: 8250,
    screeningsCheburashka: 2900,
    screeningsBuratino: 2100,
    screeningsProstokvashino: 1950,
    avgOccupancy: 65,
    avgTicketPrice: 520,
    imax: 3,
    dolbyAtmos: 5,
  },
  {
    name: "Формула Кино",
    logo: "🎦",
    cinemas: 18,
    screens: 140,
    cities: 12,
    screeningsTotal: 7000,
    screeningsCheburashka: 2450,
    screeningsBuratino: 1750,
    screeningsProstokvashino: 1680,
    avgOccupancy: 70,
    avgTicketPrice: 590,
    imax: 4,
    dolbyAtmos: 6,
  },
  {
    name: "Мираж Синема",
    logo: "✨",
    cinemas: 15,
    screens: 112,
    cities: 8,
    screeningsTotal: 5600,
    screeningsCheburashka: 1960,
    screeningsBuratino: 1400,
    screeningsProstokvashino: 1340,
    avgOccupancy: 62,
    avgTicketPrice: 480,
    imax: 2,
    dolbyAtmos: 3,
  },
  {
    name: "Люксор",
    logo: "🏛️",
    cinemas: 12,
    screens: 95,
    cities: 10,
    screeningsTotal: 4750,
    screeningsCheburashka: 1660,
    screeningsBuratino: 1190,
    screeningsProstokvashino: 1140,
    avgOccupancy: 58,
    avgTicketPrice: 450,
    imax: 1,
    dolbyAtmos: 2,
  },
];

// Movie distribution across chains
export const movieDistributionByChain = {
  "Чебурашка 2": { karo: 34, cinemaPark: 35, kinomax: 35, formulaKino: 35, mirage: 35, luxor: 35 },
  "Буратино": { karo: 25, cinemaPark: 25, kinomax: 25, formulaKino: 25, mirage: 25, luxor: 25 },
  "Простоквашино": { karo: 23, cinemaPark: 23, kinomax: 24, formulaKino: 24, mirage: 24, luxor: 24 },
};

// Daily box office race data (January 1-11, 2026)
export const movieRaceData = {
  days: ["1 янв", "2 янв", "3 янв", "4 янв", "5 янв", "6 янв", "7 янв", "8 янв", "9 янв", "10 янв", "11 янв"],
  movies: [
    {
      name: "Чебурашка 2",
      color: "#3b82f6", // blue
      values: [380, 520, 480, 420, 390, 450, 480, 520, 480, 420, 360], // млн руб/день
    },
    {
      name: "Буратино",
      color: "#f59e0b", // amber
      values: [180, 240, 220, 200, 180, 210, 220, 200, 180, 160, 140],
    },
    {
      name: "Простоквашино",
      color: "#22c55e", // green
      values: [190, 250, 230, 210, 190, 200, 210, 200, 180, 160, 150],
    },
  ],
};

// Quotes for sentiment display
export const sentimentQuotes = [
  {
    text: "Дети в восторге, смотрели не отрываясь! Чебурашка стал ещё милее.",
    sentiment: "positive" as const,
    source: "Кинопоиск",
    movie: "Чебурашка 2",
  },
  {
    text: "Визуально красиво, но сюжет слабоват. Истории нанизываются друг на друга.",
    sentiment: "negative" as const,
    source: "МСК1.ру",
    movie: "Чебурашка 2",
  },
  {
    text: "Непошлый юмор, добрая атмосфера. Идеально для семейного просмотра.",
    sentiment: "positive" as const,
    source: "Рамблер",
    movie: "Чебурашка 2",
  },
  {
    text: "Мрачновато для детской сказки. Пожалейте детей!",
    sentiment: "negative" as const,
    source: "Sport24",
    movie: "Буратино",
  },
  {
    text: "Охлобыстин в роли Печкина — это попадание в десятку!",
    sentiment: "positive" as const,
    source: "Sport24",
    movie: "Простоквашино",
  },
  {
    text: "Скучная копия мультика. Унылая халтура.",
    sentiment: "negative" as const,
    source: "IRecommend",
    movie: "Простоквашино",
  },
];

// Top movies comparison table
export const moviesComparison = [
  {
    title: "Чебурашка 2",
    revenue: 4.9,
    viewers: 9.2,
    avgTicket: 532,
    cinemas: 2324,
    shareOfScreenings: 36,
    rating: 7.1,
    sentiment: 68,
    position: 1,
  },
  {
    title: "Простоквашино",
    revenue: 2.08,
    viewers: 4.1,
    avgTicket: 507,
    cinemas: 2288,
    shareOfScreenings: 22,
    rating: 7.0,
    sentiment: 58,
    position: 2,
  },
  {
    title: "Буратино",
    revenue: 2.06,
    viewers: 3.8,
    avgTicket: 542,
    cinemas: 2306,
    shareOfScreenings: 23,
    rating: 6.7,
    sentiment: 52,
    position: 3,
  },
];
